name: Build Interactive Notebook

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths:
      - 'README.md'
      - 'convert_to_notebook.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - 'convert_to_notebook.py'

jobs:
  build-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter ipython
        
    - name: Convert README to Notebook
      run: |
        python convert_to_notebook.py README.md -o Mastering-New-Python-Libraries.ipynb
        
    - name: Upload notebook artifact
      uses: actions/upload-artifact@v4
      with:
        name: interactive-notebook
        path: Mastering-New-Python-Libraries.ipynb
        retention-days: 30
        
    - name: Create Release with Notebook (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Mastering-New-Python-Libraries.ipynb
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const notebookPath = 'Mastering-New-Python-Libraries.ipynb';
          
          if (fs.existsSync(notebookPath)) {
            const notebook = JSON.parse(fs.readFileSync(notebookPath, 'utf8'));
            const cellCount = notebook.cells.length;
            const codeCells = notebook.cells.filter(cell => cell.cell_type === 'code').length;
            const markdownCells = notebook.cells.filter(cell => cell.cell_type === 'markdown').length;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📓 Interactive Notebook Generated!
              
              An interactive Jupyter notebook has been created from your README.md changes:
              
              📊 **Notebook Statistics:**
              - Total cells: ${cellCount}
              - Code cells: ${codeCells}
              - Markdown cells: ${markdownCells}
              
              📥 **Download:** The notebook is available as an artifact in the Actions tab.
              
              🚀 **Features:**
              - All Python code blocks are now executable
              - Shell commands use \`%%bash\` magic for terminal execution
              - Interactive exploration of library examples
              - Setup cell with required imports and configuration
              
              You can download and run the notebook locally to test all examples interactively!`
            });
          } 